/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toyrobot;

public class App {

    public static void main(String[] args) {
        ToyRobotApp app = new ToyRobotApp();
        app.start();
    }
}
