/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toyrobot;

public class App {

    public static void main(String[] args) {
        ToyRobotApp toyRobotApp = new ToyRobotApp(args);
        toyRobotApp.run();
    }
}
